spring:
  application:
    name: openapi-demo
springdoc:
  api-docs:
    version: openapi_3_1
    path: /api/documentation
  swagger-ui:
    path: /api/documentation/swagger-ui.html
    groups-order: desc