spring:
    application:
      name: openapi-demo
springdoc:
    paths-to-exclude: /**/internal/**
    api-docs:
      path: /specification/openapi
      version: openapi_3_0
    swagger-ui:
      path: /specification/openapi/index.html