spring:
  application:
    name: openapi-demo
springdoc:
  api-docs:
    version: openapi_3_1
    path: /api/documentation
  swagger-ui:
    disable-swagger-default-url: true
    path: /api/documentation/OpenAPI.html